### ISSUE TITLE
cmake presets binaryDir override

### ISSUE THREAD

**Issue by smanders** [externpro/externpro#6]
### background
as described in the issue when cmake presets were introduced to externpro https://github.com/externpro/externpro/issues/2#issuecomment-1949125779

it's expected that there will be two files in the root of a project leveraging externpro's cmake preset support
1. CMakePresets.json
1. CMakePresetsBase.json

the CMakePresetsBase.json file allows a project to define its own `config-base`
* project-specific `cacheVariables`
* `binaryDir`
* any other `configurePresets` it wishes to utilize https://cmake.org/cmake/help/v3.28/manual/cmake-presets.7.html#configure-preset

`binaryDir`
> An optional string representing the path to the output binary directory.

example CMakePresetsBase.json https://github.com/externpro/externpro/blob/24.03/cmake/presets/CMakePresetsBase.json#L7

by default `binaryDir` is `${sourceDir}/_bld-${presetName}` (so `_bld-Linux` and `_bld-Windows` *in* the source directory) and project repos have a `.gitignore` with `_bld*/` so all directories starting with `_bld` are git ignored

**Comment by smanders** [comment]
however, it's not an uncommon request that people want to override the default `binaryDir`... I'm okay with developers editing the CMakePresetsBase.json file so that it's a sibling directory to the source directory
```diff
diff --git a/CMakePresetsBase.json b/CMakePresetsBase.json
index 09653d8..1078c68 100644
--- a/CMakePresetsBase.json
+++ b/CMakePresetsBase.json
@@ -4,7 +4,7 @@
     {
       "name": "config-base",
       "hidden": true,
-      "binaryDir": "${sourceDir}/_bld-${presetName}"
+      "binaryDir": "${sourceParentDir}/_bld-${sourceDirName}-${presetName}"
     }
   ]
 }
```
but I don't want to commit and change the default! I prefer the build directory to be *under* the source directory

launching the build of a project that uses build containers and cmake presets is two simple steps
```
./docker-compose.sh
cmake --workflow --preset=Linux
```
but if you change the `binaryDir` to `${sourceParentDir}` instead of the default `${sourceDir}` this fails, because the build container can't create a directory in the parent

```
$ cmake --workflow --preset=Linux
Executing workflow step 1 of 4: configure preset "Linux"

CMake Error: Unable to (re)create the private pkgRedirects directory:
/bpvol/_bld-foobar-Linux/CMakeFiles/pkgRedirects
```

and now launching a build would be multiple steps that need explanation
```
./docker-compose.sh
cd ../workspace/<source-dir>
cmake --workflow --preset=Linux
```
and if there are source directories of other projects that are siblings we would need to adjust to make their binaryDir's unique

so many things are more straight-forward if the build (binary) directory is *under* the source directory

**Comment by smanders** [comment]
a request from the developer developing CI
> With the cmake presets, it creates a `_bld-${presetName}` in the source directory. Is there anyway to change that via command line to not be in the source directory? The reason I ask is because right now, the CI system has the work dir, and in it is the source directory and the build directory as siblings.... I could change that, but that is a much bigger change...
> Or could we add a preset that if a environment variable was set, we use the path in the environment variable, otherwise we default to `${sourceDir}/_bld-${presetName}`?

**Comment by smanders** [comment]
I spent a fair amount of time exploring options...
* trying to use environment variables
* conditionals in the preset files (something similar to `isLinux` that I'm currently using)
* including alternative json files that specifically only set `binaryDir`

nothing was really working like I wanted it to and the complexity was also ramping up...

it came down to this: provide a way on the command line to override `binaryDir`

and my plan is to add a cmake script as part of externpro (launchWorkflow.cmake) that will modify the `binaryDir` line in CMakePresetsBase.json, launch the workflow, and then reset the CMakePresetsBase.json back to what it was

pass in `binaryDir` with `-D`, and escape any `$` with `\$`:
```
cmake -DbinaryDir="\${sourceParentDir}/_bld-\${sourceDirName}-\${presetName}" -P .devcontainer/cmake/presets/launchWorkflow.cmake
```

**Comment by camerbam** [comment]
Figured I should list my reasons here why I have put my binary dir outside of my source dir 😄 
- When I run git clean -xdf, it doesn't blow away my build.
- I also use a _fortify folder for the binary dir for fortify scans. I don't want to get _fortify folders mixed up with actual binary dirs. I realize, this can be fixed by putting _fortify in every .gitignore, but by having it as a sibling, it worked for every repo, regardless of their .gitignore.
- When searching through the code for something, I didn't have to use the ide specific way of always ignoring any type of binary directory I had. I realize that every tool has a way of excluding directories, but it became a non issue if it was outside.

This is how I have structured my folders:
src/
&nbsp;\<microservice name\>
&nbsp;&nbsp;\<source code\>
&nbsp;&nbsp;\<build dir\>
&nbsp;&nbsp;\<fortify folder\>
&nbsp;&nbsp;\<any other pertinent files for the microservice, configs, databases, UnitTestResults, etc\>

Every project was laid out like that, so that every file I need for a project is in that folder. It also allowed me to have a directory called _bld for each project. 

As far as the multiple commands go, I actually already use a docker-compose.override.yml and change the initial directory to the workspace. So with the presets, I could just change that to be workspace/\<source-dir\>

Anyways, that is why I do the _bld directory as a sibling 😄

**Comment by smanders** [comment]
I realize that developers do what works for them and I don't want to change that, but
* I want `git clean -xdf` to blow away my build
* I would simply use `_bldfortify` for fortify scans which would be gitignore'd without any changes to .gitignore
* I want an ide to see things in the binary directory (especially now with devel packages putting libraries/headers in `_deps`)

I'm glad docker-compose.override.yml provides a way for developers to quickly get to the directory they want to start in and that it isn't too painful to have the _bld directory as a sibling for those who prefer it that way!

**Comment by smanders** [comment]
the CI system appears to be relying on this now https://isrhub.usurf.usu.edu/cfrandsen/VantageCI/pull/21/files#diff-99dded4a0fe1781b52bd3fd5997035c996d6242422edf53b0b6c6b856e43e1c0

**Comment by smanders** [comment]
palam v1.10.10.5 was built using CI 24.04.1 and the binaryDir override was used and worked
https://isrhub.usurf.usu.edu/palam/palam/actions/runs/13275/job/100359#step:4:23
```
cmake -DbinaryDir=/__w/palam/palam/_bld -P .devcontainer/cmake/presets/launchWorkflow.cmake
```

closing as completed with commit to main branch referenced above
